// <auto-generated />
using DescubraSeuFuturo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DescubraSeuFuturo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110171052_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DescubraSeuFuturo.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RamoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RamoId");

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Ramo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Ramos", (string)null);
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Curso", b =>
                {
                    b.HasOne("DescubraSeuFuturo.Models.Ramo", "Ramo")
                        .WithMany("Cursos")
                        .HasForeignKey("RamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ramo");
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Ramo", b =>
                {
                    b.HasOne("DescubraSeuFuturo.Models.Area", "Area")
                        .WithMany("Ramos")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Area", b =>
                {
                    b.Navigation("Ramos");
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Ramo", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
