// <auto-generated />
using DescubraSeuFuturo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DescubraSeuFuturo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251111200940_SeedInicial")]
    partial class SeedInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DescubraSeuFuturo.Models.Competencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NivelDemanda")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SetorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("Competencias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Pensamento Crítico"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Resolução de Problemas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Trabalho em Equipe"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Aprendizado Contínuo"
                        });
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DuracaoHoras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plataforma")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrilhaAprendizadoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrilhaAprendizadoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Análise de Dados"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Desenvolvimento Web"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Design de Experiência do Usuário"
                        });
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Empregabilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .HasColumnType("TEXT");

                    b.Property<double>("TaxaCrescimento")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Empregabilidades");
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Habilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Habilidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Python"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Comunicação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Gestão de Tempo"
                        });
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaAtuacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mentores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaAtuacao = "Tecnologia",
                            Nome = "Ana Silva"
                        },
                        new
                        {
                            Id = 2,
                            AreaAtuacao = "Design",
                            Nome = "Carlos Almeida"
                        },
                        new
                        {
                            Id = 3,
                            AreaAtuacao = "Empreendedorismo",
                            Nome = "Beatriz Santos"
                        });
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Setores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Design"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Educação"
                        });
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.TrilhaAprendizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompetenciaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompetenciaId");

                    b.ToTable("TrilhasAprendizado");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Fundamentos de lógica e algoritmos",
                            Nome = "Introdução à Programação"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Noções básicas de design centrado no usuário",
                            Nome = "UX Design para Iniciantes"
                        });
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjetivoCarreira")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Competencia", b =>
                {
                    b.HasOne("DescubraSeuFuturo.Models.Setor", "Setor")
                        .WithMany("Competencias")
                        .HasForeignKey("SetorId");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Curso", b =>
                {
                    b.HasOne("DescubraSeuFuturo.Models.TrilhaAprendizado", "TrilhaAprendizado")
                        .WithMany("Cursos")
                        .HasForeignKey("TrilhaAprendizadoId");

                    b.Navigation("TrilhaAprendizado");
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.TrilhaAprendizado", b =>
                {
                    b.HasOne("DescubraSeuFuturo.Models.Competencia", "Competencia")
                        .WithMany()
                        .HasForeignKey("CompetenciaId");

                    b.Navigation("Competencia");
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.Setor", b =>
                {
                    b.Navigation("Competencias");
                });

            modelBuilder.Entity("DescubraSeuFuturo.Models.TrilhaAprendizado", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
